/*
 * This file has been auto generated by srcript, see genCimSpinner.rb
 */
#include "cimspinner_config.h"
//#define SPINNER_RAINBOW
//#define SPINNER_RAINBOWMIX
//#define SPINNER_ROTATINGHEART
//#define SPINNER_ANG
//#define SPINNER_ANG8
//#define SPINNER_ANGMIX
//#define SPINNER_LOADINGRING
//#define SPINNER_CLOCK
//#define SPINNER_PULSAR
//#define SPINNER_DOUBLEFADEPULSAR
//#define SPINNER_TWINPULSAR
//#define SPINNER_FADEPULSAR
//#define SPINNER_FADEPULSARSQUARE
//#define SPINNER_CIRCULARLINES
//#define SPINNER_DOTS
//#define SPINNER_VDOTS
//#define SPINNER_BOUNCEDOTS
//#define SPINNER_ZIPDOTS
//#define SPINNER_DOTSTOPOINTS
//#define SPINNER_DOTSTOBAR
//#define SPINNER_WAVEDOTS
//#define SPINNER_FADEDOTS
//#define SPINNER_THREEDOTS
//#define SPINNER_FIVEDOTS
//#define SPINNER_4CALEIDOSPCOPE
//#define SPINNER_MULTIFADEDOTS
//#define SPINNER_THICKTOSIN
//#define SPINNER_SCALEDOTS
//#define SPINNER_SQUARESPINS
//#define SPINNER_MOVINGDOTS
//#define SPINNER_ROTATEDOTS
//#define SPINNER_ORIONDOTS
//#define SPINNER_GALAXYDOTS
//#define SPINNER_TWINANG
//#define SPINNER_FILLING
//#define SPINNER_FILLINGMEM
//#define SPINNER_TOPUP
//#define SPINNER_TWINANG180
//#define SPINNER_TWINANG360
//#define SPINNER_INCDOTS
//#define SPINNER_INCFULLDOTS
//#define SPINNER_FADEBARS
//#define SPINNER_FADETRIS
//#define SPINNER_BARSROTATEFADE
//#define SPINNER_BARSSCALEMIDDLE
//#define SPINNER_ANGTWIN
//#define SPINNER_ARCROTATION
//#define SPINNER_ARCFADE
//#define SPINNER_SIMPLEARCFADE
//#define SPINNER_SQUARESTROKEFADE
//#define SPINNER_ASCIISYMBOLPOINTS
//#define SPINNER_TEXTFADING
//#define SPINNER_SEVENSEGMENTS
//#define SPINNER_SQUARESTROKEFILL
//#define SPINNER_SQUARESTROKELOADING
//#define SPINNER_SQUARELOADING
//#define SPINNER_FILLEDARCFADE
//#define SPINNER_POINTSROLLER
//#define SPINNER_POINTSARCBOUNCE
//#define SPINNER_FILLEDARCCOLOR
//#define SPINNER_FILLEDARCRING
//#define SPINNER_ARCWEDGES
//#define SPINNER_TWINBALL
//#define SPINNER_SOLARBALLS
//#define SPINNER_SOLARSCALEBALLS
//#define SPINNER_SOLARARCS
//#define SPINNER_MOVINGARCS
//#define SPINNER_RAINBOWCIRCLE
//#define SPINNER_BOUNCEBALL
//#define SPINNER_PULSARBALL
//#define SPINNER_INCSCALEDOTS
//#define SPINNER_SOMESCALEDOTS
//#define SPINNER_ANGTRIPLE
//#define SPINNER_ANGECLIPSE
//#define SPINNER_INGYANG
//#define SPINNER_GOOEYBALLS
//#define SPINNER_DOTSLOADING
//#define SPINNER_ROTATEGOOEYBALLS
//#define SPINNER_HERBERTBALLS
//#define SPINNER_HERBERTBALLS3D
//#define SPINNER_ROTATETRIANGLES
//#define SPINNER_ROTATESHAPES
//#define SPINNER_SINSQUARES
//#define SPINNER_MOONLINE
//#define SPINNER_CIRCLEDROP
//#define SPINNER_SURROUNDEDINDICATOR
//#define SPINNER_WIFIINDICATOR
//#define SPINNER_TRIANGLESSELECTOR
//#define SPINNER_CAMERA
//#define SPINNER_FLOWINGGRADIENT
//#define SPINNER_ROTATESEGMENTS
//#define SPINNER_LEMNISCATE
//#define SPINNER_ROTATEGEAR
//#define SPINNER_ROTATEWHEEL
//#define SPINNER_ATOM
//#define SPINNER_PATTERNRINGS
//#define SPINNER_PATTERNECLIPSE
//#define SPINNER_PATTERNSPHERE
//#define SPINNER_RINGSYNCHRONOUS
//#define SPINNER_RINGWATERMARKS
//#define SPINNER_ROTATEDATOM
//#define SPINNER_RAINBOWBALLS
//#define SPINNER_RAINBOWSHOT
//#define SPINNER_SPIRAL
//#define SPINNER_SPIRALEYE
//#define SPINNER_BARCHARTSINE
//#define SPINNER_BARCHARTADVSINE
//#define SPINNER_BARCHARTADVSINEFADE
//#define SPINNER_BARCHARTRAINBOW
//#define SPINNER_BLOCKS
//#define SPINNER_TWINBLOCKS
//#define SPINNER_SQUARERANDOMDOTS
//#define SPINNER_SCALEBLOCKS
//#define SPINNER_SCALESQUARES
//#define SPINNER_SQUISHSQUARE
//#define SPINNER_FLUID
//#define SPINNER_FLUIDPOINTS
//#define SPINNER_ARCPOLARFADE
//#define SPINNER_ARCPOLARRADIUS
//#define SPINNER_CALEIDOSCOPE
//#define SPINNER_HBODOTS
//#define SPINNER_MOONDOTS
//#define SPINNER_TWINHBODOTS
//#define SPINNER_THREEDOTSSTAR
//#define SPINNER_SINEARCS
//#define SPINNER_TRIANGLESSHIFT
//#define SPINNER_POINTSSHIFT
//#define SPINNER_SWINGDOTS
//#define SPINNER_CIRCULARPOINTS
//#define SPINNER_CURVEDCIRCLE
//#define SPINNER_MODCIRCLE
//#define SPINNER_DNADOTS
//#define SPINNER_3SMUGGLEDOTS
//#define SPINNER_ROTATESEGMENTSPULSAR
//#define SPINNER_SPLINEANG

#pragma once
#ifdef __cplusplus
extern "C" {
#endif

#ifndef CIMSPINNER_API
  #define CIMSPINNER_API
#endif

CIMSPINNER_API void SpinnerRainbow(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerRainbowEx(const char *label, float radius, float thickness, const ImColor color, float speed,float ang_min, float ang_max, int arcs, int mode);
CIMSPINNER_API void SpinnerRainbowMix(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerRainbowMixEx(const char *label, float radius, float thickness, const ImColor color, float speed,float ang_min, float ang_max, int arcs, int mode);
CIMSPINNER_API void SpinnerRotatingHeart(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerRotatingHeartEx(const char *label, float radius, float thickness, const ImColor color, float speed,float ang_min);
CIMSPINNER_API void SpinnerAng(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerAngEx(const char *label, float radius, float thickness,const ImColor color, const ImColor bg, float speed, float angle, int mode);
CIMSPINNER_API void SpinnerAng8(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerAng8Ex(const char *label, float radius, float thickness,const ImColor color, const ImColor bg, float speed, float angle, int mode, float rkoef);
CIMSPINNER_API void SpinnerAngMix(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerAngMixEx(const char *label, float radius, float thickness,const ImColor color, float speed, float angle, int arcs, int mode);
CIMSPINNER_API void SpinnerLoadingRing(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerLoadingRingEx(const char *label, float radius, float thickness,const ImColor color, const ImColor bg, float speed, int segments);
CIMSPINNER_API void SpinnerClock(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerClockEx(const char *label, float radius, float thickness,const ImColor color, const ImColor bg, float speed);
CIMSPINNER_API void SpinnerPulsar(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerPulsarEx(const char *label, float radius, float thickness,const ImColor bg, float speed, bool sequence, float angle, int mode);
CIMSPINNER_API void SpinnerDoubleFadePulsar(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDoubleFadePulsarEx(const char *label, float radius, float thickness,const ImColor bg, float speed);
CIMSPINNER_API void SpinnerTwinPulsar(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerTwinPulsarEx(const char *label, float radius, float thickness,const ImColor color, float speed, int rings, int mode);
CIMSPINNER_API void SpinnerFadePulsar(const char *label, float radius);
CIMSPINNER_API void SpinnerFadePulsarEx(const char *label, float radius,const ImColor color, float speed, int rings, int mode);
CIMSPINNER_API void SpinnerFadePulsarSquare(const char *label, float radius);
CIMSPINNER_API void SpinnerFadePulsarSquareEx(const char *label, float radius,const ImColor color, float speed, int rings, int mode);
CIMSPINNER_API void SpinnerCircularLines(const char *label, float radius);
CIMSPINNER_API void SpinnerCircularLinesEx(const char *label, float radius,const ImColor color, float speed, int lines, int mode);
CIMSPINNER_API void SpinnerDots(const char *label, float *nextdot, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsEx(const char *label, float *nextdot, float radius, float thickness,const ImColor color, float speed, size_t dots, float minth, int mode);
CIMSPINNER_API void SpinnerVDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerVDotsEx(const char *label, float radius, float thickness,const ImColor color, const ImColor bgcolor, float speed, size_t dots, size_t mdots, int mode);
CIMSPINNER_API void SpinnerBounceDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBounceDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots, int mode);
CIMSPINNER_API void SpinnerZipDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerZipDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots);
CIMSPINNER_API void SpinnerDotsToPoints(const char *label, float radius, float thickness, float offset_k);
CIMSPINNER_API void SpinnerDotsToPointsEx(const char *label, float radius, float thickness, float offset_k,const ImColor color, float speed, size_t dots);
CIMSPINNER_API void SpinnerDotsToBar(const char *label, float radius, float thickness, float offset_k);
CIMSPINNER_API void SpinnerDotsToBarEx(const char *label, float radius, float thickness, float offset_k,const ImColor color, float speed, size_t dots);
CIMSPINNER_API void SpinnerWaveDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerWaveDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt);
CIMSPINNER_API void SpinnerFadeDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerFadeDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt, int mode);
CIMSPINNER_API void SpinnerThreeDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerThreeDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt);
CIMSPINNER_API void SpinnerFiveDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerFiveDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt);
CIMSPINNER_API void Spinner4Caleidospcope(const char *label, float radius, float thickness);
CIMSPINNER_API void Spinner4CaleidospcopeEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt);
CIMSPINNER_API void SpinnerMultiFadeDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerMultiFadeDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt);
CIMSPINNER_API void SpinnerThickToSin(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerThickToSinEx(const char *label, float radius, float thickness,const ImColor color, float speed, int nt, int lt, int mode);
CIMSPINNER_API void SpinnerScaleDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerScaleDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt);
CIMSPINNER_API void SpinnerSquareSpins(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSquareSpinsEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerMovingDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerMovingDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots);
CIMSPINNER_API void SpinnerRotateDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerRotateDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int dots, int mode);
CIMSPINNER_API void SpinnerOrionDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerOrionDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int arcs);
CIMSPINNER_API void SpinnerGalaxyDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerGalaxyDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int arcs);
CIMSPINNER_API void SpinnerTwinAng(const char *label, float radius1, float radius2, float thickness);
CIMSPINNER_API void SpinnerTwinAngEx(const char *label, float radius1, float radius2, float thickness,const ImColor color1, const ImColor color2, float speed, float angle, int mode);
CIMSPINNER_API void SpinnerFilling(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerFillingEx(const char *label, float radius, float thickness,const ImColor color1, const ImColor color2, float speed);
CIMSPINNER_API void SpinnerFillingMem(const char *label, float radius, float thickness, const ImColor color, ImColor colorbg, float speed);
CIMSPINNER_API void SpinnerTopup(const char *label, float radius1, float radius2);
CIMSPINNER_API void SpinnerTopupEx(const char *label, float radius1, float radius2,const ImColor color, const ImColor fg, const ImColor bg, float speed);
CIMSPINNER_API void SpinnerTwinAng180(const char *label, float radius1, float radius2, float thickness);
CIMSPINNER_API void SpinnerTwinAng180Ex(const char *label, float radius1, float radius2, float thickness,const ImColor color1, const ImColor color2, float speed, float angle, int mode);
CIMSPINNER_API void SpinnerTwinAng360(const char *label, float radius1, float radius2, float thickness);
CIMSPINNER_API void SpinnerTwinAng360Ex(const char *label, float radius1, float radius2, float thickness,const ImColor color1, const ImColor color2, float speed1, float speed2, int mode);
CIMSPINNER_API void SpinnerIncDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerIncDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots);
CIMSPINNER_API void SpinnerIncFullDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerIncFullDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots);
CIMSPINNER_API void SpinnerFadeBars(const char *label, float w);
CIMSPINNER_API void SpinnerFadeBarsEx(const char *label, float w,const ImColor color, float speed, size_t bars, bool scale);
CIMSPINNER_API void SpinnerFadeTris(const char *label, float radius);
CIMSPINNER_API void SpinnerFadeTrisEx(const char *label, float radius,const ImColor color, float speed, size_t dim, bool scale, int mode);
CIMSPINNER_API void SpinnerBarsRotateFade(const char *label, float rmin, float rmax , float thickness);
CIMSPINNER_API void SpinnerBarsRotateFadeEx(const char *label, float rmin, float rmax , float thickness,const ImColor color, float speed, size_t bars);
CIMSPINNER_API void SpinnerBarsScaleMiddle(const char *label, float w);
CIMSPINNER_API void SpinnerBarsScaleMiddleEx(const char *label, float w,const ImColor color, float speed, size_t bars);
CIMSPINNER_API void SpinnerAngTwin(const char *label, float radius1, float radius2, float thickness);
CIMSPINNER_API void SpinnerAngTwinEx(const char *label, float radius1, float radius2, float thickness,const ImColor color, const ImColor bg, float speed, float angle, size_t arcs, int mode);
CIMSPINNER_API void SpinnerArcRotation(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerArcRotationEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t arcs, int mode);
CIMSPINNER_API void SpinnerArcFade(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerArcFadeEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t arcs, int mode);
CIMSPINNER_API void SpinnerSimpleArcFade(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSimpleArcFadeEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerSquareStrokeFade(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSquareStrokeFadeEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerAsciiSymbolPoints(const char *label, const char* text, float radius, float thickness);
CIMSPINNER_API void SpinnerAsciiSymbolPointsEx(const char *label, const char* text, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerTextFading(const char *label, const char* text, float radius, float fsize);
CIMSPINNER_API void SpinnerTextFadingEx(const char *label, const char* text, float radius, float fsize,const ImColor color, float speed);
CIMSPINNER_API void SpinnerSevenSegments(const char *label, const char* text, float radius, float thickness);
CIMSPINNER_API void SpinnerSevenSegmentsEx(const char *label, const char* text, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerSquareStrokeFill(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSquareStrokeFillEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerSquareStrokeLoading(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSquareStrokeLoadingEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerSquareLoading(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSquareLoadingEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerFilledArcFade(const char *label, float radius);
CIMSPINNER_API void SpinnerFilledArcFadeEx(const char *label, float radius,const ImColor color, float speed, size_t arcs, int mode);
CIMSPINNER_API void SpinnerPointsRoller(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerPointsRollerEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t points, int circles, float rspeed);
CIMSPINNER_API void SpinnerPointsArcBounce(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerPointsArcBounceEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t points, int circles, float rspeed);
CIMSPINNER_API void SpinnerFilledArcColor(const char *label, float radius);
CIMSPINNER_API void SpinnerFilledArcColorEx(const char *label, float radius,const ImColor color, const ImColor bg, float speed, size_t arcs);
CIMSPINNER_API void SpinnerFilledArcRing(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerFilledArcRingEx(const char *label, float radius, float thickness,const ImColor color, const ImColor bg, float speed, size_t arcs);
CIMSPINNER_API void SpinnerArcWedges(const char *label, float radius);
CIMSPINNER_API void SpinnerArcWedgesEx(const char *label, float radius,const ImColor color, float speed, size_t arcs, int mode);
CIMSPINNER_API void SpinnerTwinBall(const char *label, float radius1, float radius2, float thickness, float b_thickness);
CIMSPINNER_API void SpinnerTwinBallEx(const char *label, float radius1, float radius2, float thickness, float b_thickness,const ImColor ball, const ImColor bg, float speed, size_t balls, int mode);
CIMSPINNER_API void SpinnerSolarBalls(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSolarBallsEx(const char *label, float radius, float thickness,const ImColor ball, const ImColor bg, float speed, size_t balls);
CIMSPINNER_API void SpinnerSolarScaleBalls(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSolarScaleBallsEx(const char *label, float radius, float thickness,const ImColor ball, float speed, size_t balls);
CIMSPINNER_API void SpinnerSolarArcs(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSolarArcsEx(const char *label, float radius, float thickness,const ImColor ball, const ImColor bg, float speed, size_t balls);
CIMSPINNER_API void SpinnerMovingArcs(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerMovingArcsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t arcs);
CIMSPINNER_API void SpinnerRainbowCircle(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerRainbowCircleEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t arcs, float mode);
CIMSPINNER_API void SpinnerBounceBall(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBounceBallEx(const char *label, float radius, float thickness,const ImColor color, float speed, int dots, bool shadow);
CIMSPINNER_API void SpinnerPulsarBall(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerPulsarBallEx(const char *label, float radius, float thickness,const ImColor color, float speed, bool shadow, int mode);
CIMSPINNER_API void SpinnerIncScaleDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerIncScaleDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots, float angle, int mode);
CIMSPINNER_API void SpinnerSomeScaleDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSomeScaleDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots, int mode);
CIMSPINNER_API void SpinnerAngTriple(const char *label, float radius1, float radius2, float radius3, float thickness);
CIMSPINNER_API void SpinnerAngTripleEx(const char *label, float radius1, float radius2, float radius3, float thickness,const ImColor c1, const ImColor c2, const ImColor c3, float speed, float angle);
CIMSPINNER_API void SpinnerAngEclipse(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerAngEclipseEx(const char *label, float radius, float thickness,const ImColor color, float speed, float angle);
CIMSPINNER_API void SpinnerIngYang(const char *label, float radius, float thickness, bool reverse, float yang_detlta_r);
CIMSPINNER_API void SpinnerIngYangEx(const char *label, float radius, float thickness, bool reverse, float yang_detlta_r,const ImColor colorI, const ImColor colorY, float speed, float angle, int mode);
CIMSPINNER_API void SpinnerGooeyBalls(const char *label, float radius, const ImColor color, float speed);
CIMSPINNER_API void SpinnerGooeyBallsEx(const char *label, float radius, const ImColor color, float speed,int mode);
CIMSPINNER_API void SpinnerDotsLoading(const char *label, float radius, float thickness, const ImColor color, const ImColor bg, float speed);
CIMSPINNER_API void SpinnerRotateGooeyBalls(const char *label, float radius, float thickness, const ImColor color, float speed, int balls);
CIMSPINNER_API void SpinnerRotateGooeyBallsEx(const char *label, float radius, float thickness, const ImColor color, float speed, int balls,int mode);
CIMSPINNER_API void SpinnerHerbertBalls(const char *label, float radius, float thickness, const ImColor color, float speed, int balls);
CIMSPINNER_API void SpinnerHerbertBalls3D(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerRotateTriangles(const char *label, float radius, float thickness, const ImColor color, float speed, int tris);
CIMSPINNER_API void SpinnerRotateTrianglesEx(const char *label, float radius, float thickness, const ImColor color, float speed, int tris,int mode);
CIMSPINNER_API void SpinnerRotateShapes(const char *label, float radius, float thickness, const ImColor color, float speed, int shapes, int pnt);
CIMSPINNER_API void SpinnerSinSquares(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerSinSquaresEx(const char *label, float radius, float thickness, const ImColor color, float speed,int mode);
CIMSPINNER_API void SpinnerMoonLine(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerMoonLineEx(const char *label, float radius, float thickness,const ImColor color, const ImColor bg, float speed, float angle);
CIMSPINNER_API void SpinnerCircleDrop(const char *label, float radius, float thickness, float thickness_drop);
CIMSPINNER_API void SpinnerCircleDropEx(const char *label, float radius, float thickness, float thickness_drop,const ImColor color, const ImColor bg, float speed, float angle);
CIMSPINNER_API void SpinnerSurroundedIndicator(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSurroundedIndicatorEx(const char *label, float radius, float thickness,const ImColor color, const ImColor bg, float speed);
CIMSPINNER_API void SpinnerWifiIndicator(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerWifiIndicatorEx(const char *label, float radius, float thickness,const ImColor color, const ImColor bg, float speed, float cangle, int dots);
CIMSPINNER_API void SpinnerTrianglesSelector(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerTrianglesSelectorEx(const char *label, float radius, float thickness,const ImColor color, const ImColor bg, float speed, size_t bars);
typedef ImColor LeafColor(int);
CIMSPINNER_API void SpinnerCamera(const char *label, float radius, float thickness, LeafColor *leaf_color);
CIMSPINNER_API void SpinnerCameraEx(const char *label, float radius, float thickness, LeafColor *leaf_color,float speed, size_t bars, int mode);
CIMSPINNER_API void SpinnerFlowingGradient(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerFlowingGradientEx(const char *label, float radius, float thickness,const ImColor color, const ImColor bg, float speed, float angle);
CIMSPINNER_API void SpinnerRotateSegments(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerRotateSegmentsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t arcs, size_t layers, int mode);
CIMSPINNER_API void SpinnerLemniscate(const char* label, float radius, float thickness);
CIMSPINNER_API void SpinnerLemniscateEx(const char* label, float radius, float thickness,const ImColor color, float speed, float angle);
CIMSPINNER_API void SpinnerRotateGear(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerRotateGearEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t pins);
CIMSPINNER_API void SpinnerRotateWheel(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerRotateWheelEx(const char *label, float radius, float thickness,const ImColor bg_color, const ImColor color, float speed, size_t pins);
CIMSPINNER_API void SpinnerAtom(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerAtomEx(const char *label, float radius, float thickness,const ImColor color, float speed, int elipses);
CIMSPINNER_API void SpinnerPatternRings(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerPatternRingsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int elipses);
CIMSPINNER_API void SpinnerPatternEclipse(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerPatternEclipseEx(const char *label, float radius, float thickness,const ImColor color, float speed, int elipses, float delta_a, float delta_y);
CIMSPINNER_API void SpinnerPatternSphere(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerPatternSphereEx(const char *label, float radius, float thickness,const ImColor color, float speed, int elipses);
CIMSPINNER_API void SpinnerRingSynchronous(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerRingSynchronousEx(const char *label, float radius, float thickness,const ImColor color, float speed, int elipses);
CIMSPINNER_API void SpinnerRingWatermarks(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerRingWatermarksEx(const char *label, float radius, float thickness,const ImColor color, float speed, int elipses);
CIMSPINNER_API void SpinnerRotatedAtom(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerRotatedAtomEx(const char *label, float radius, float thickness,const ImColor color, float speed, int elipses, int mode);
CIMSPINNER_API void SpinnerRainbowBalls(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerRainbowBallsEx(const char *label, float radius, float thickness, const ImColor color, float speed,int balls, int mode, int rings, int mx);
CIMSPINNER_API void SpinnerRainbowShot(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerRainbowShotEx(const char *label, float radius, float thickness, const ImColor color, float speed,int balls, int mode);
CIMSPINNER_API void SpinnerSpiral(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSpiralEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t arcs);
CIMSPINNER_API void SpinnerSpiralEye(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSpiralEyeEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerBarChartSine(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerBarChartSineEx(const char *label, float radius, float thickness, const ImColor color, float speed,int bars, int mode);
CIMSPINNER_API void SpinnerBarChartAdvSine(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerBarChartAdvSineEx(const char *label, float radius, float thickness, const ImColor color, float speed,int mode);
CIMSPINNER_API void SpinnerBarChartAdvSineFade(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerBarChartAdvSineFadeEx(const char *label, float radius, float thickness, const ImColor color, float speed,int mode);
CIMSPINNER_API void SpinnerBarChartRainbow(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerBarChartRainbowEx(const char *label, float radius, float thickness, const ImColor color, float speed,int bars, int mode);
CIMSPINNER_API void SpinnerBlocks(const char *label, float radius, float thickness, const ImColor bg, const ImColor color, float speed);
CIMSPINNER_API void SpinnerTwinBlocks(const char *label, float radius, float thickness, const ImColor bg, const ImColor color, float speed);
CIMSPINNER_API void SpinnerSquareRandomDots(const char *label, float radius, float thickness, const ImColor bg, const ImColor color, float speed);
CIMSPINNER_API void SpinnerScaleBlocks(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerScaleBlocksEx(const char *label, float radius, float thickness, const ImColor color, float speed,int mode);
CIMSPINNER_API void SpinnerScaleSquares(const char *label, float radius, float thikness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerSquishSquare(const char *label, float radius, const ImColor color, float speed);
CIMSPINNER_API void SpinnerFluid(const char *label, float radius, const ImColor color, float speed);
CIMSPINNER_API void SpinnerFluidEx(const char *label, float radius, const ImColor color, float speed,int bars);
CIMSPINNER_API void SpinnerFluidPoints(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerFluidPointsEx(const char *label, float radius, float thickness, const ImColor color, float speed,size_t dots, float delta);
CIMSPINNER_API void SpinnerArcPolarFade(const char *label, float radius);
CIMSPINNER_API void SpinnerArcPolarFadeEx(const char *label, float radius,const ImColor color, float speed, size_t arcs, int mode);
CIMSPINNER_API void SpinnerArcPolarRadius(const char *label, float radius);
CIMSPINNER_API void SpinnerArcPolarRadiusEx(const char *label, float radius,const ImColor color, float speed, size_t arcs, int mode);
CIMSPINNER_API void SpinnerCaleidoscope(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerCaleidoscopeEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t arcs, int mode);
CIMSPINNER_API void SpinnerHboDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerHboDotsEx(const char *label, float radius, float thickness,const ImColor color, float minfade, float ryk, float speed, size_t dots, int mode);
CIMSPINNER_API void SpinnerMoonDots(const char *label, float radius, float thickness, const ImColor first, const ImColor second);
CIMSPINNER_API void SpinnerMoonDotsEx(const char *label, float radius, float thickness, const ImColor first, const ImColor second,float speed);
CIMSPINNER_API void SpinnerTwinHboDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerTwinHboDotsEx(const char *label, float radius, float thickness,const ImColor color, float minfade, float ryk, float speed, size_t dots, float delta);
CIMSPINNER_API void SpinnerThreeDotsStar(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerThreeDotsStarEx(const char *label, float radius, float thickness,const ImColor color, float minfade, float ryk, float speed, float delta);
CIMSPINNER_API void SpinnerSineArcs(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSineArcsEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerTrianglesShift(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerTrianglesShiftEx(const char *label, float radius, float thickness,const ImColor color, const ImColor bg, float speed, size_t bars);
CIMSPINNER_API void SpinnerPointsShift(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerPointsShiftEx(const char *label, float radius, float thickness,const ImColor color, const ImColor bg, float speed, size_t bars);
CIMSPINNER_API void SpinnerSwingDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSwingDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerCircularPoints(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerCircularPointsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lines);
CIMSPINNER_API void SpinnerCurvedCircle(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerCurvedCircleEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t circles);
CIMSPINNER_API void SpinnerModCircle(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerModCircleEx(const char *label, float radius, float thickness,const ImColor color, float ang_min, float ang_max, float speed);
CIMSPINNER_API void SpinnerDnaDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDnaDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt, float delta, bool mode);
CIMSPINNER_API void Spinner3SmuggleDots(const char *label, float radius, float thickness);
CIMSPINNER_API void Spinner3SmuggleDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt, float delta, bool mode);
CIMSPINNER_API void SpinnerRotateSegmentsPulsar(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerRotateSegmentsPulsarEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t arcs, size_t layers);
CIMSPINNER_API void SpinnerSplineAng(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSplineAngEx(const char *label, float radius, float thickness,const ImColor color, const ImColor bg, float speed, float angle, int mode);

CIMSPINNER_API void demoSpinners();
#ifdef __cplusplus
}
#endif
